pages:
    - Home: 'index.md'
    - Products:
        - A:
            - Add to Cart Notification: 'add_to_cart_notification.md'
            - Auto Reward Points: 'auto_reward_points.md'
            - Auto Translate: 'auto_translate.md'
        - C:
            - Canned Messages: 'canned_messages.md'
            - Clean SEO URL: 'clean_seo_url.md'
            - Colour Code: 'colour_code.md'
            - Colour Picker: 'colour_picker.md'
            - Country IP Rules: 'country_ip_rules.md'
            - Coupon Manager: 'coupon_manager.md'
            - Custom Product Fields: 'custom_product_fields.md'
            - Customer Group Membership: 'customer_group_membership.md'
            - Customer Group Restrictions: 'customer_group_restrictions.md'
        - D:
            - Default Option Value: 'default_option_value.md'
            - Dependent Options: 'dependent_options.md'
            - Disable Products: 'disable_products.md'
        - E:
            - eNETS Integration: 'enets_integration.md'
        - F:
            - Facebook Comments: 'facebook_comments.md'
            - Facebook Login: 'facebook_login.md'
            - Facebook Share: 'facebook_share.md'
            - Feature Categories: 'feature_categories.md'
            - Follow Up Email: 'follow_up_email.md'
            - Footer Position: 'footer_position.md'
        - H:
            - Hover Image: 'hover_image.md'
        - I:
            - Image Crop: 'image_crop.md'
        - L:
            - Live Price Update: 'live_price_update.md'
            - Logic Message Integration: 'logic_message_integration.md'
        - M:
            - Main Image: 'main_image.md'
            - Marquee Text: 'marquee_text.md'
            - Mass Order History Update: 'mass_order_history_update.md'
            - Mega Menu: 'mega_menu.md'
            - MultiStore Manager: 'multistore_manager.md'
        - N:
            - Newsletter: 'newsletter.md'
        - O:
            - Option Description: 'option_description.md'
            - Option Image: 'option_image.md'
            - Option Value Equals Sign: 'option_value_equals_sign.md'
            - Options with Quantities: 'options_with_quantities.md'
            - Order Limitation: 'order_limitation.md'
        - P:
            - Popup History Manager: 'popup_history_manager.md'
            - Popup Login: 'popup_login.md'
            - Popup Order Manager: 'popup_order_manager.md'
            - Pretty HTML Email: 'pretty_html_email.md'
            - Price As Low As: 'price_as_low_as.md'
            - Price Manager: 'price_manager.md'
            - Product Date End: 'product_date_end.md'
            - Product Geo Zone: 'product_geo_zone.md'
            - Product Stock Mobile App: 'product_stock_mobile_app.md'
            - Purchase Order: 'purchase_order.md'
            - Purchase Store Credits: 'purchase_store_credits.md'
        - Q:
            - Quick Checkout: 'quick_checkout.md'
            - Quick Order Update: 'quick_order_update.md'
        - R:
            - Recently Sold: 'recently_sold.md'
            - Recently Viewed: 'recently_viewed.md'
            - Recover Abandoned Cart: 'recover_abandoned_cart.md'
            - Redirection Manager: 'redirection_manager.md'
            - Related Pro: 'related_pro.md'
        - S:
            - Send From China: 'send_from_china.md'
            - SEO Pack: 'seo_pack.md'
            - Serial Key Extension: 'serial_key_extension.md'
            - Shopping Cart: 'shopping_cart.md'
            - Show Price in Cart: 'show_price_in_cart.md'
            - Side Contact Form: 'side_contact_form.md'
            - Sidebar Menu: 'sidebar_menu.md'
            - Specials Countdown: 'specials_countdown.md'
            - Specials Timer: 'specials_timer.md'
        - T:
            - Testimonials Slider: 'testimonials_slider.md'
            - Tiered Pricing: 'tiered_pricing.md'
            - Two Factor Authentication SMS: 'two_factor_authentication_sms.md'
        - W:
            - Watermark: 'watermark.md'
        - X:
            - Xero Integration: 'xero_integration.md'
site_name: MarketInSG Documentations
site_description: MarketInSG product documentations - OpenCart extensions Singapore.
copyright: MarketInSG &copy; 2017
remote_branch: gh-pages
theme: material
site_favicon: 'images/favicon.png'
extra:
  palette:
    primary: 'deep orange'
    accent: 'amber'
  logo: 'images/logo.png'
  social:
    - type: 'github'
      link: 'https://www.github.com/Equotix'
    - type: 'facebook'
      link: 'https://www.facebook.com/Equotix'