pages:
    - Home: 'index.md'
    - Products:
        - Add to Cart Notification: 'add_to_cart_notification.md'
        - Auto Reward Points: 'auto_reward_points.md'
        - Auto Translate: 'auto_translate.md'
        - Canned Messages: 'canned_messages.md'
        - Clean SEO URL: 'clean_seo_url.md'
        - Colour Code: 'colour_code.md'
        - Colour Picker: 'colour_picker.md'
        - Country IP Rules: 'country_ip_rules.md'
        - Coupon Manager: 'coupon_manager.md'
        - Custom Product Fields: 'custom_product_fields.md'
        - Customer Group Membership: 'customer_group_membership.md'
        - Customer Group Restrictions: 'customer_group_restrictions.md'
        - Dependent Options: 'dependent_options.md'
        - Follow Up Email: 'follow_up_email.md'
        - Option Image: 'option_image.md'
        - Quick Checkout: 'quick_checkout.md'
        - Shopping Cart: 'shopping_cart.md'
        - Xero Integration: 'xero_integration.md'
site_name: MarketInSG Documentations
site_description: MarketInSG product documentations - OpenCart extensions Singapore.
copyright: MarketInSG &copy; 2017
remote_branch: gh-pages
theme: material
site_favicon: 'images/favicon.png'
extra:
  palette:
    primary: 'deep orange'
    accent: 'amber'
  logo: 'images/logo.png'
  social:
    - type: 'github'
      link: 'https://www.github.com/Equotix'
    - type: 'facebook'
      link: 'https://www.facebook.com/Equotix'