pages:
    - Home: 'index.md'
    - Products:
        - Add to Cart Notification: 'add_to_cart_notification.md'
        - Auto Reward Points: 'auto_reward_points.md'
        - Colour Picker: 'colour_picker.md'
        - Dependent Options: 'dependent_options.md'
        - Quick Checkout: 'quick_checkout.md'
site_name: MarketInSG Documentations
site_description: MarketInSG product documentations - OpenCart extensions Singapore.
copyright: MarketInSG &copy; 2017
remote_branch: gh-pages
theme: material
site_favicon: 'images/favicon.png'
extra:
  palette:
    primary: 'deep orange'
    accent: 'amber'
  logo: 'images/logo.png'
  social:
    - type: 'github'
      link: 'https://www.github.com/Equotix'
    - type: 'facebook'
      link: 'https://www.facebook.com/Equotix'