pages:
    - Home: 'index.md'
    - Products:
        - Add to Cart Notification: 'add_to_cart_notification.md'
site_name: MarketInSG Documentations
site_description: MarketInSG product documentations - OpenCart extensions Singapore.
copyright: MarketInSG &copy; 2017
repo_url: https://github.com/Equotix/opencart-docs
remote_branch: gh-pages
theme: material
extra:
  palette:
    primary: 'deep orange'
    accent: 'amber'